### ISSUE TITLE
error compiling due to multi-hashing

### ISSUE THREAD

**Issue by nfriacowboy** [vigcoin/pool-runner#1]
Hi, first of all congrats for the effort!!!

This is the error LOG

node_modules/@vigcoin/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/src/multihashing.o
../src/multihashing.cc: In function ‘void cryptonight(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/multihashing.cc:375:41: error: no matching function for call to ‘v8::Value::ToUint32()’
             variant = args[1]->ToUint32()->Uint32Value();
                                         ^
In file included from /installFolder/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../src/multihashing.cc:1:
/installFolder/.node-gyp/10.5.0/include/node/v8.h:2406:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^
/installFolder/.node-gyp/10.5.0/include/node/v8.h:2406:44: note:   candidate expects 1 argument, 0 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-const-variable’
multihashing.target.mk:150: recipe for target 'Release/obj.target/multihashing/src/multihashing.o' failed
make: *** [Release/obj.target/multihashing/src/multihashing.o] Error 1
make: Leaving directory '/installFolder/pool/node_modules/@vigcoin/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /installFolder/pool/node_modules/@vigcoin/multi-hashing
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN pool-runner@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vigcoin/multi-hashing@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vigcoin/multi-hashing@0.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I'm on

Ubuntu 16.04
nodejs v10.5.0
npm 6.1.0

Regards and thanks for your time and expertice

**Comment by calidion** [comment]
@nfriacowboy  

please try v8 instead.
currently v10 is not workable.
